server:
  port: 8080
spring:
  cloud:
    gateway:
      httpclient:
        response-timeout: 60000
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: backend_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.app.cloud.filter.JwtAuthenticationFilter: DEBUG
